server:
  port: 8080
spring:
  application:
    name: "ms_smart_cats"
  devtools:
    add-properties: false
  profiles:
    include: null
  datasource:
    url: "jdbc:postgresql://localhost:5434/smartcats_db"
    username: "smartcats"
    password: "12345678"
    driverClassName: "org.postgresql.Driver"
  jpa:
    databasePlatform: "org.hibernate.dialect.PostgreSQLDialect"
  rabbitmq:
    host: localhost
    port: 5672
    username: mecuella
    password: 12345678
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
